<section class="nc-panel" id="people"><div class="nc-panel-heading"><div><h2>Personnel et soldes</h2><p>Lecture commune au dashboard et à l’export.</p></div></div>
<div class="nc-table-wrap"><table class="nc-table"><thead><tr><th>Salarié</th><th>Poste</th><th>Département</th><th>Ancienneté</th><th>Initial</th><th>Acquis</th><th>Majorations</th><th>Consommé</th><th>En attente</th><th>Disponible</th></tr></thead><tbody>
@foreach ($personnel as $row) @php($employee = $row['employee']) @php($balance = $row['balance']) <tr><td>{{ $employee->name() }}</td><td>{{ $employee->job_title }}</td><td>{{ $employee->department?->name ?? '—' }}</td><td>{{ $employee->hire_date?->diffInYears(now()) ?? '—' }} ans</td><td>{{ $balance['initial_balance'] }}</td><td>{{ $balance['accrued'] }}</td><td>{{ $balance['bonuses'] }}</td><td>{{ $balance['consumed'] }}</td><td>{{ $balance['pending'] }}</td><td><strong>{{ $balance['available'] }}</strong></td></tr>@endforeach
</tbody></table></div>

<div class="nc-panel-heading"><div><h3>Profils RH des collaborateurs</h3><p>Complétez l’adresse Microsoft, la date d’embauche et l’éligibilité aux congés.</p></div></div>
@foreach ($personnel as $row) @php($employee = $row['employee'])<form id="employee-leave-form-{{ $employee->id }}" method="POST" action="{{ route('admin.leaves.employees.update', $employee) }}">@csrf @method('PUT')</form>@endforeach
<div class="nc-table-wrap"><table class="nc-table leave-admin-table"><thead><tr><th>Salarié</th><th>Email Microsoft</th><th>Date d’embauche</th><th>Éligible</th><th></th></tr></thead><tbody>
@foreach ($personnel as $row) @php($employee = $row['employee'])<tr><td><strong>{{ $employee->name() }}</strong><br><span class="nc-muted">{{ $employee->department?->name ?? 'Sans département' }}</span></td><td><input form="employee-leave-form-{{ $employee->id }}" name="email" type="email" value="{{ $employee->email }}" aria-label="Email Microsoft de {{ $employee->name() }}"></td><td><input form="employee-leave-form-{{ $employee->id }}" name="hire_date" type="date" value="{{ $employee->hire_date?->format('Y-m-d') }}" aria-label="Date d’embauche de {{ $employee->name() }}"></td><td><input form="employee-leave-form-{{ $employee->id }}" name="leave_eligible" type="checkbox" value="1" @checked($employee->leave_eligible) aria-label="{{ $employee->name() }} est éligible aux congés"></td><td><button form="employee-leave-form-{{ $employee->id }}" class="nc-ghost" type="submit">Enregistrer</button></td></tr>@endforeach
</tbody></table></div>{{ $personnel->links() }}</section>
