<section class="nc-panel" id="rules"><div class="nc-panel-heading"><div><h2>Types et règles</h2><p>Chaque sauvegarde crée une version applicable uniquement aux futures demandes.</p></div></div>
<div class="leave-rule-list">@foreach ($leaveTypes as $type)<details class="leave-rule-card"><summary><strong>{{ $type->name }}</strong><span>{{ $type->unit->label() }} · v{{ $type->rules->max('version') ?? 0 }}</span></summary>
<form method="POST" action="{{ route('admin.leaves.types.update', $type) }}" class="nc-form-grid">@csrf @method('PUT')
<label class="nc-field"><span>Libellé métier</span><input name="name" value="{{ $type->name }}" required></label>
<label class="nc-field"><span>Catégorie</span><select name="category">@foreach (['leave'=>'Congé','permission'=>'Permission','authorization'=>'Autorisation','suspension'=>'Suspension'] as $value=>$label)<option value="{{ $value }}" @selected($type->category->value === $value)>{{ $label }}</option>@endforeach</select></label>
<label class="nc-field"><span>Unité</span><select name="unit">@foreach (\App\Enums\LeaveUnit::cases() as $unit)<option value="{{ $unit->value }}" @selected($type->unit === $unit)>{{ ucfirst($unit->label()) }}</option>@endforeach</select></label>
<label class="nc-field"><span>Quota annuel</span><input type="number" step=".01" min="0" name="quota" value="{{ $type->quota }}"></label>
<label class="nc-field"><span>Durée maximale</span><input type="number" step=".01" min="0" name="maximum_duration" value="{{ $type->maximum_duration }}"></label>
<label class="nc-field"><span>Préavis (heures)</span><input type="number" min="0" name="notice_hours" value="{{ $type->notice_hours }}" required></label>
<label class="nc-field"><span>Date d’effet</span><input type="date" name="effective_from" value="{{ now()->addDay()->toDateString() }}" required><small>La modification ne concerne que les futures demandes.</small></label>
<label class="nc-field"><span>Référence juridique</span><textarea name="legal_reference">{{ $type->legal_reference }}</textarea></label>
<label class="nc-mini-check"><input type="checkbox" name="is_paid" value="1" @checked($type->is_paid)> Payé</label><label class="nc-mini-check"><input type="checkbox" name="counts_against_balance" value="1" @checked($type->counts_against_balance)> Déduit le congé annuel</label><label class="nc-mini-check"><input type="checkbox" name="requires_attachment" value="1" @checked($type->requires_attachment)> Justificatif requis</label><label class="nc-mini-check"><input type="checkbox" name="is_active" value="1" @checked($type->is_active)> Actif</label>
<button class="nc-button" type="submit">Créer la nouvelle version</button></form></details>@endforeach</div></section>

<div class="leave-admin-grid"><section class="nc-panel" id="calendar"><div class="nc-panel-heading"><div><h2>Calendrier des jours fériés</h2><p>Exclus automatiquement des durées en jours ouvrables.</p></div></div><form method="POST" action="{{ route('admin.leaves.holidays.store') }}" class="leave-filter">@csrf<label class="nc-field"><span>Date</span><input type="date" name="date" required></label><label class="nc-field"><span>Libellé</span><input name="name" required></label><button class="nc-button">Ajouter</button></form><ul class="leave-holiday-list">@forelse($holidays as $holiday)<li><span>{{ $holiday->date->format('d/m/Y') }} — {{ $holiday->name }}</span><form method="POST" action="{{ route('admin.leaves.holidays.destroy', $holiday) }}">@csrf @method('DELETE')<button class="nc-ghost" aria-label="Supprimer {{ $holiday->name }}">Supprimer</button></form></li>@empty<li>Aucun jour férié configuré.</li>@endforelse</ul></section>
<section class="nc-panel" id="imports"><div class="nc-panel-heading"><div><h2>Imports et exports</h2><p>Les filtres actifs sont repris dans le classeur.</p></div></div><div class="nc-actions"><a class="nc-button is-secondary" href="{{ route('admin.leaves.export', request()->query()) }}">Exporter .xlsx</a><a class="nc-ghost" href="{{ route('admin.leaves.import.template') }}">Modèle d’import</a></div></section>
<section class="nc-panel" id="workflow"><div class="nc-panel-heading"><div><h2>Circuit de validation</h2><p>Superviseur → RH / Admin-Finance → DG.</p></div></div><ol class="leave-timeline"><li>Impact équipe</li><li>Conformité RH</li><li>Décision finale</li></ol></section></div>
