<section class="nc-panel" id="rules"><div class="nc-panel-heading"><div><h2>Types et règles</h2><p>Chaque sauvegarde crée une version applicable uniquement aux futures demandes.</p></div></div>
<div class="leave-rule-list">@foreach ($leaveTypes as $type)<details class="leave-rule-card"><summary><strong>{{ $type->name }}</strong><span>{{ $type->unit->label() }} · v{{ $type->rules->max('version') ?? 0 }}</span></summary>
<form method="POST" action="{{ route('admin.leaves.types.update', $type) }}" class="nc-form-grid">@csrf @method('PUT')
<label class="nc-field"><span>Libellé métier</span><input name="name" value="{{ $type->name }}" required></label>
<label class="nc-field"><span>Catégorie</span><select name="category">@foreach (['leave'=>'Congé','permission'=>'Permission','authorization'=>'Autorisation','suspension'=>'Suspension'] as $value=>$label)<option value="{{ $value }}" @selected($type->category->value === $value)>{{ $label }}</option>@endforeach</select></label>
<label class="nc-field"><span>Unité</span><select name="unit">@foreach (\App\Enums\LeaveUnit::cases() as $unit)<option value="{{ $unit->value }}" @selected($type->unit === $unit)>{{ ucfirst($unit->label()) }}</option>@endforeach</select></label>
<label class="nc-field"><span>Quota annuel</span><input type="number" step=".01" min="0" name="quota" value="{{ $type->quota }}"></label>
<label class="nc-field"><span>Durée maximale</span><input type="number" step=".01" min="0" name="maximum_duration" value="{{ $type->maximum_duration }}"></label>
<label class="nc-field"><span>Préavis (heures)</span><input type="number" min="0" name="notice_hours" value="{{ $type->notice_hours }}" required></label>
<label class="nc-field"><span>Renouvellements maximum</span><input type="number" min="0" max="20" name="maximum_renewals" value="{{ $type->maximum_renewals }}" required><small>Information de politique ; aucun parcours de renouvellement automatisé n’est actif.</small></label>
<label class="nc-field"><span>Portée demandeur</span><select name="requester_scope"><option value="employee" @selected($type->requester_scope === 'employee')>Collaborateur</option><option value="admin" @selected($type->requester_scope === 'admin')>Administration uniquement</option><option value="both" @selected($type->requester_scope === 'both')>Collaborateur et administration</option></select></label>
<label class="nc-field"><span>Règles d’éligibilité (JSON)</span><textarea name="eligibility_rules" placeholder='{"minimum_service_months":12}'>{{ $type->eligibility_rules ? json_encode($type->eligibility_rules, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) : '' }}</textarea><small>Critères acceptés : minimum_service_months, allowed_entities, allowed_locations, allowed_job_titles.</small></label>
<label class="nc-field"><span>Date d’effet</span><input type="date" name="effective_from" value="{{ now()->addDay()->toDateString() }}" required><small>La modification ne concerne que les futures demandes.</small></label>
<label class="nc-field"><span>Référence juridique</span><textarea name="legal_reference">{{ $type->legal_reference }}</textarea></label>
<label class="nc-mini-check"><input type="checkbox" name="is_paid" value="1" @checked($type->is_paid)> Payé</label><label class="nc-mini-check"><input type="checkbox" name="counts_against_balance" value="1" @checked($type->counts_against_balance)> Déduit le congé annuel</label><label class="nc-mini-check"><input type="checkbox" name="requires_attachment" value="1" @checked($type->requires_attachment)> Justificatif requis</label><label class="nc-mini-check"><input type="checkbox" name="is_active" value="1" @checked($type->is_active)> Actif</label>
<button class="nc-button" type="submit" data-tooltip-title="Versionner la règle" data-tooltip="Crée une règle à la date d’effet choisie sans modifier les demandes déjà enregistrées.">Créer la nouvelle version</button></form></details>@endforeach</div></section>
