<section class="nc-panel" id="settings"><div class="nc-panel-heading"><div><h2>Paramètres de calcul et de documents</h2><p>Ces valeurs s’appliquent aux futures opérations et chaque modification est historisée.</p></div></div>
<form method="POST" action="{{ route('admin.leaves.settings.update') }}" class="nc-form-grid" data-dirty-form>@csrf @method('PUT')
<input type="hidden" name="settings_updated_at" value="{{ $settings->get('monthly_accrual_days')?->updated_at?->toISOString() }}">
<label class="nc-field"><span>Jours acquis par mois</span><input type="number" step="0.01" min="0" max="31" name="monthly_accrual_days" value="{{ old('monthly_accrual_days', $settings->get('monthly_accrual_days')?->value ?? '2.5') }}" required></label>
<label class="nc-field"><span>Politique d’acquisition</span><select name="accrual_policy" required>@foreach (['end_of_month' => 'Fin de mois', 'start_of_month' => 'Début de mois', 'prorated' => 'Prorata'] as $value => $label)<option value="{{ $value }}" @selected(old('accrual_policy', $settings->get('accrual_policy')?->value ?? 'end_of_month') === $value)>{{ $label }}</option>@endforeach</select></label>
<label class="nc-field"><span>Nom du signataire</span><input name="LEAVE_CERTIFICATE_SIGNATORY_NAME" value="{{ old('LEAVE_CERTIFICATE_SIGNATORY_NAME', $settings->get('LEAVE_CERTIFICATE_SIGNATORY_NAME')?->value ?? config('leaves.certificate_signatory_name')) }}"></label>
<label class="nc-field"><span>Fonction du signataire</span><input name="LEAVE_CERTIFICATE_SIGNATORY_TITLE" value="{{ old('LEAVE_CERTIFICATE_SIGNATORY_TITLE', $settings->get('LEAVE_CERTIFICATE_SIGNATORY_TITLE')?->value ?? config('leaves.certificate_signatory_title')) }}"><small>Image de signature : {{ $signatureExists ? 'disponible' : 'absente (facultative)' }}.</small></label>
<label class="nc-field"><span>Motif du changement</span><textarea name="change_reason" maxlength="1000" placeholder="Pourquoi ce réglage change-t-il ?">{{ old('change_reason') }}</textarea></label>
<div class="nc-actions"><button class="nc-button" type="submit"><i data-lucide="save" aria-hidden="true"></i>Enregistrer les paramètres</button><span class="unsaved-indicator" data-unsaved-indicator hidden>Modifications non enregistrées</span></div>
</form></section>

<section class="nc-panel" id="rules"><div class="nc-panel-heading"><div><h2>Types et règles</h2><p>Chaque sauvegarde crée une version applicable uniquement aux futures demandes.</p></div></div>
<div class="leave-rule-list">@foreach ($leaveTypes as $type)<details class="leave-rule-card"><summary><strong>{{ $type->name }}</strong><span>{{ $type->unit->label() }} · v{{ $type->rules->max('version') ?? 0 }}</span></summary>
<form method="POST" action="{{ route('admin.leaves.types.update', $type) }}" class="nc-form-grid">@csrf @method('PUT')
<label class="nc-field"><span>Libellé métier</span><input name="name" value="{{ $type->name }}" required></label>
<label class="nc-field"><span>Catégorie</span><select name="category">@foreach (['leave'=>'Congé','permission'=>'Permission','authorization'=>'Autorisation','suspension'=>'Suspension'] as $value=>$label)<option value="{{ $value }}" @selected($type->category->value === $value)>{{ $label }}</option>@endforeach</select></label>
<label class="nc-field"><span>Unité</span><select name="unit">@foreach (\App\Enums\LeaveUnit::cases() as $unit)<option value="{{ $unit->value }}" @selected($type->unit === $unit)>{{ ucfirst($unit->label()) }}</option>@endforeach</select></label>
<label class="nc-field"><span>Quota annuel</span><input type="number" step=".01" min="0" name="quota" value="{{ $type->quota }}"></label>
<label class="nc-field"><span>Durée maximale</span><input type="number" step=".01" min="0" name="maximum_duration" value="{{ $type->maximum_duration }}"></label>
<label class="nc-field"><span>Préavis (heures)</span><input type="number" min="0" name="notice_hours" value="{{ $type->notice_hours }}" required></label>
<label class="nc-field"><span>Renouvellements maximum</span><input type="number" min="0" max="20" name="maximum_renewals" value="{{ $type->maximum_renewals }}" required><small>Information de politique ; aucun parcours de renouvellement automatisé n’est actif.</small></label>
<label class="nc-field"><span>Portée demandeur</span><select name="requester_scope"><option value="employee" @selected($type->requester_scope === 'employee')>Collaborateur</option><option value="admin" @selected($type->requester_scope === 'admin')>Administration uniquement</option><option value="both" @selected($type->requester_scope === 'both')>Collaborateur et administration</option></select></label>
<label class="nc-field"><span>Règles d’éligibilité (JSON)</span><textarea name="eligibility_rules" placeholder='{"minimum_service_months":12}'>{{ $type->eligibility_rules ? json_encode($type->eligibility_rules, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) : '' }}</textarea><small>Critères acceptés : minimum_service_months, allowed_entities, allowed_locations, allowed_job_titles.</small></label>
<label class="nc-field"><span>Date d’effet</span><input type="date" name="effective_from" value="{{ now()->addDay()->toDateString() }}" required><small>La modification ne concerne que les futures demandes.</small></label>
<label class="nc-field"><span>Référence juridique</span><textarea name="legal_reference">{{ $type->legal_reference }}</textarea></label>
<label class="nc-mini-check"><input type="checkbox" name="is_paid" value="1" @checked($type->is_paid)> Payé</label><label class="nc-mini-check"><input type="checkbox" name="counts_against_balance" value="1" @checked($type->counts_against_balance)> Déduit le congé annuel</label><label class="nc-mini-check"><input type="checkbox" name="requires_attachment" value="1" @checked($type->requires_attachment)> Justificatif requis</label><label class="nc-mini-check"><input type="checkbox" name="is_active" value="1" @checked($type->is_active)> Actif</label>
<button class="nc-button" type="submit">Créer la nouvelle version</button></form></details>@endforeach</div></section>

<div class="leave-admin-grid"><section class="nc-panel" id="calendar"><div class="nc-panel-heading"><div><h2>Calendrier des jours fériés</h2><p>Exclus automatiquement des durées en jours ouvrables.</p></div></div><form method="POST" action="{{ route('admin.leaves.holidays.store') }}" class="leave-filter">@csrf<label class="nc-field"><span>Date</span><input type="date" name="date" required></label><label class="nc-field"><span>Libellé</span><input name="name" required></label><button class="nc-button">Ajouter</button></form><ul class="leave-holiday-list">@forelse($holidays as $holiday)<li><span>{{ $holiday->date->format('d/m/Y') }} — {{ $holiday->name }}</span><form method="POST" action="{{ route('admin.leaves.holidays.destroy', $holiday) }}">@csrf @method('DELETE')<button class="nc-ghost" aria-label="Supprimer {{ $holiday->name }}">Supprimer</button></form></li>@empty<li>Aucun jour férié configuré.</li>@endforelse</ul></section>
<section class="nc-panel" id="imports"><div class="nc-panel-heading"><div><h2>Imports et exports</h2><p>Initialisez les soldes depuis un CSV, puis exportez la situation filtrée.</p></div></div>
@if (session('import_report')) @php($report = session('import_report'))<div class="nc-alert is-success" role="status"><strong>Résultat du dernier import</strong><p>{{ $report['rows_read'] ?? $report['read'] ?? 0 }} lignes lues · {{ $report['rows_imported'] ?? $report['matched'] ?? 0 }} créées · {{ $report['rows_updated'] ?? 0 }} mises à jour · {{ $report['rows_skipped'] ?? 0 }} ignorées.</p>@if ($report['errors'] ?? [])<ul>@foreach ($report['errors'] as $error)<li>{{ $error }}</li>@endforeach</ul>@endif</div>@endif
<form method="POST" action="{{ route('admin.leaves.import') }}" enctype="multipart/form-data" class="nc-form-grid">@csrf
<label class="nc-field"><span>Date de référence</span><input type="date" name="reference_date" value="{{ old('reference_date') }}" required><small>Date à laquelle les soldes du fichier ont été arrêtés.</small></label>
<label class="nc-field"><span>Fichier des soldes</span><input type="file" name="file" accept=".csv,.txt,text/csv,text/plain" required><small>CSV ou TXT, avec une ligne par collaborateur.</small></label>
<button class="nc-button" type="submit"><i data-lucide="upload" aria-hidden="true"></i>Importer les soldes initiaux</button>
</form>
<div class="nc-actions"><a class="nc-button is-secondary" href="{{ route('admin.leaves.export', request()->query()) }}">Exporter .xlsx</a><a class="nc-ghost" href="{{ route('admin.leaves.import.template') }}">Modèle d’import</a></div></section>
</div>

<section class="nc-panel" id="workflow"><div class="nc-panel-heading"><div><h2>Responsabilités de validation</h2><p>Affectez les responsables du circuit : responsable hiérarchique → RH / Admin-Finance → DG.</p></div></div>
<form method="POST" action="{{ route('admin.leaves.validators.store') }}" class="nc-form-grid">@csrf
<label class="nc-field"><span>Validateur</span><select name="employee_id" required>@foreach ($employees as $employee)<option value="{{ $employee->id }}" @selected(old('employee_id') == $employee->id)>{{ $employee->name() }}</option>@endforeach</select></label>
<label class="nc-field"><span>Responsabilité</span><select name="step_key" required><option value="supervisor" @selected(old('step_key', 'supervisor') === 'supervisor')>Responsable hiérarchique</option><option value="hr" @selected(old('step_key') === 'hr')>RH / Admin-Finance</option><option value="dg" @selected(old('step_key') === 'dg')>DG / Direction</option></select></label>
<label class="nc-field"><span>Portée</span><select name="scope" required><option value="global" @selected(old('scope', 'global') === 'global')>Toutes les demandes</option><option value="department" @selected(old('scope') === 'department')>Un département</option><option value="employee" @selected(old('scope') === 'employee')>Un collaborateur</option></select></label>
<label class="nc-field"><span>Département concerné</span><select name="department_id"><option value="">Non applicable</option>@foreach ($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id') == $department->id)>{{ $department->name }}</option>@endforeach</select><small>Obligatoire pour une portée par département.</small></label>
<label class="nc-field"><span>Collaborateur concerné</span><select name="target_employee_id"><option value="">Non applicable</option>@foreach ($employees as $employee)<option value="{{ $employee->id }}" @selected(old('target_employee_id') == $employee->id)>{{ $employee->name() }}</option>@endforeach</select><small>Obligatoire pour une portée individuelle.</small></label>
<label class="nc-mini-check"><input type="hidden" name="notify_by_email" value="0"><input type="checkbox" name="notify_by_email" value="1" @checked((string) old('notify_by_email', '1') === '1')> Notifier ce validateur par email</label>
<button class="nc-button" type="submit"><i data-lucide="user-check" aria-hidden="true"></i>Ajouter la responsabilité</button>
</form>
<div class="nc-table-wrap"><table class="nc-table"><thead><tr><th>Validateur</th><th>Responsabilité</th><th>Portée</th><th>Notifications</th><th>État</th><th>Actions</th></tr></thead><tbody>
@forelse ($validators as $validator)<tr><td>{{ $validator->employee?->name() }}</td><td>{{ $validator->step_key === 'supervisor' ? 'Responsable hiérarchique' : $validator->stepLabel() }}</td><td>{{ match ($validator->scope) { 'department' => $validator->department?->name ?? 'Département non défini', 'employee' => $validator->targetEmployee?->name() ?? 'Collaborateur non défini', default => 'Toutes les demandes' } }}</td><td>{{ $validator->notify_by_email ? 'Email actif' : 'Sans email' }}</td><td><span class="leave-status {{ $validator->is_active ? 'is-approved' : 'is-cancelled' }}">{{ $validator->is_active ? 'actif' : 'inactif' }}</span></td><td><div class="leave-inline-form">
<form method="POST" action="{{ route('admin.leaves.validators.update', $validator) }}" class="leave-inline-form">@csrf @method('PUT')<label class="nc-mini-check"><input type="checkbox" name="notify_by_email" value="1" @checked($validator->notify_by_email)> Email</label><label class="nc-mini-check"><input type="checkbox" name="is_active" value="1" @checked($validator->is_active)> Actif</label><button class="nc-ghost" type="submit">Enregistrer</button></form>
<form method="POST" action="{{ route('admin.leaves.validators.destroy', $validator) }}" onsubmit="return confirm('Supprimer cette responsabilité de validation ?')">@csrf @method('DELETE')<button class="nc-ghost danger" type="submit">Supprimer</button></form>
</div></td></tr>@empty<tr><td colspan="6"><div class="nc-empty">Aucune responsabilité nominative configurée.</div></td></tr>@endforelse
</tbody></table></div></section>
